### ISSUE TITLE
et2lst result "ampm" doesn't have the AM/PM add-on

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#86]
The function `et2lst`, given an ephemeris epoch, computes the local solar time for an object on the surface of a body at a specified longitude. Here are the inputs and returned values:

```
    Inputs:
      float  et   = Epoch in seconds past J2000 epoch.
      int    body = ID-code of the body of interest.
      float  lon  = Longitude of surface point (radians).
      string type = Type of longitude, "PLANETOCENTRIC", etc.
    
    Returns:
      int    hr   = Local hour on a "24 hour" clock.
      int    mn   = Minutes past the hour.
      int    sc   = Seconds past the minute.
      string time = String giving local time on 24 hour clock.
      string ampm = String giving time on AM/PM scale.
```

The `ampm` value is missing its 'AM'/'PM'. For example, When this code runs:

```
import cspyce as cs
from gettestkernels import CoreKernels


cs.furnsh(CoreKernels.testMetaKernel)
et = cs.str2et("2004 may 17 16:30:00")
hr, mn, sc, time, ampm = cs.et2lst(
    et, 399, 281.49521300000004 * cs.rpd(), "planetocentric")

print(ampm)
```
The current result is `11:19:22`. The expected result is `11:19:22 A.M.`. Since the result represents a 12-hour timescale, this label is necessary to correctly represent the time.

**Comment by fyellin** [comment]
Whoever wrote this interface thought that ampm returned "A.M." or "P.M."
rather than the entire time.

There are two occurrences of 10 that need to be changed to TIMELEN in
my_et2lst() in cpsyce0.i. (Lines 2859ff). Apparently 10 characters wasn't
long enough to write out the result, so it didn't even try.

 Change both occurrences of ampm[10] to ampm[TIMELEN] and the code should
work fine.

Reassigning to Emilie.
